Repository orbitjs/orbit, pull requests merged in 2019-03, with the labels that each got.

#596 Add Store.rebase()
  packages/@orbit/store/src/store.ts
  packages/@orbit/store/test/store-test.ts
Labels: enhancement

#604 Cleanup and extend store tests
  packages/@orbit/store/src/store.ts
  packages/@orbit/store/test/store-test.ts
Labels: internal

#605 Extends #603 to fix related errors
  packages/@orbit/record-cache/src/operators/async-query-operators.ts
  packages/@orbit/record-cache/src/operators/sync-query-operators.ts
  packages/@orbit/record-cache/test/async-record-cache-test.ts
  packages/@orbit/record-cache/test/sync-record-cache-test.ts
Labels: bug

#606 Do not reset persisting sources on initalize
  packages/@orbit/indexeddb/src/cache.ts
  packages/@orbit/local-storage/src/cache.ts
Labels: bug

#610 Add tests to verify local storage + indexeddb sources are not reset on initialization
  packages/@orbit/indexeddb/test/source-test.ts
  packages/@orbit/local-storage/test/source-test.ts
Labels: internal
