Repository orbitjs/orbit, pull requests merged in 2019-05, with the labels that each got.

#631 Switch to yarn
  lerna.json
  package-lock.json
  package.json
  packages/@orbit/coordinator/package-lock.json
  packages/@orbit/coordinator/package.json
  packages/@orbit/coordinator/yarn.lock
  packages/@orbit/core/package-lock.json
  packages/@orbit/core/package.json
  packages/@orbit/core/yarn.lock
  packages/@orbit/data/package-lock.json
  packages/@orbit/data/package.json
  packages/@orbit/data/yarn.lock
  packages/@orbit/immutable/package-lock.json
  packages/@orbit/immutable/package.json
  packages/@orbit/immutable/yarn.lock
  packages/@orbit/indexeddb-bucket/package-lock.json
  packages/@orbit/indexeddb-bucket/package.json
  packages/@orbit/indexeddb-bucket/yarn.lock
  packages/@orbit/indexeddb/package-lock.json
  packages/@orbit/indexeddb/package.json
  packages/@orbit/indexeddb/yarn.lock
  packages/@orbit/integration-tests/package-lock.json
  packages/@orbit/integration-tests/package.json
  packages/@orbit/integration-tests/yarn.lock
  packages/@orbit/jsonapi/package-lock.json
  packages/@orbit/jsonapi/package.json
  packages/@orbit/jsonapi/yarn.lock
  packages/@orbit/local-storage-bucket/package-lock.json
  packages/@orbit/local-storage-bucket/package.json
  packages/@orbit/local-storage-bucket/yarn.lock
  packages/@orbit/local-storage/package-lock.json
  packages/@orbit/local-storage/package.json
  packages/@orbit/local-storage/yarn.lock
  packages/@orbit/record-cache/package-lock.json
  packages/@orbit/record-cache/package.json
  packages/@orbit/record-cache/yarn.lock
  packages/@orbit/serializers/package-lock.json
  packages/@orbit/serializers/package.json
  packages/@orbit/serializers/yarn.lock
  packages/@orbit/store/package-lock.json
  packages/@orbit/store/package.json
  packages/@orbit/store/yarn.lock
  packages/@orbit/utils/package-lock.json
  packages/@orbit/utils/package.json
  packages/@orbit/utils/yarn.lock
  yarn.lock
Labels: internal

#627 Polymorphic Relationships
  packages/@orbit/data/src/exception.ts
  packages/@orbit/data/src/schema.ts
  packages/@orbit/record-cache/src/operation-processors/async-schema-validation-processor.ts
  packages/@orbit/record-cache/src/operation-processors/sync-schema-validation-processor.ts
  packages/@orbit/record-cache/test/async-record-cache-test.ts
  packages/@orbit/record-cache/test/operation-processors/schema-validation-processor-test.ts
  packages/@orbit/record-cache/test/sync-record-cache-test.ts
Labels: enhancement

#637 Dependent record deletion not updating
  packages/@orbit/memory/test/memory-cache-test.ts
  packages/@orbit/record-cache/src/operation-processors/async-cache-integrity-processor.ts
  packages/@orbit/record-cache/src/operation-processors/sync-cache-integrity-processor.ts
  packages/@orbit/record-cache/src/operation-processors/utils/cache-integrity-utils.ts
  packages/@orbit/record-cache/test/async-record-cache-test.ts
  packages/@orbit/record-cache/test/operation-processors/cache-integrity-processor-test.ts
  packages/@orbit/record-cache/test/operation-processors/schema-consistency-processor-test.ts
  packages/@orbit/record-cache/test/sync-record-cache-test.ts
Labels: bug

#644 Update language level of module target to es2017
  packages/@orbit/coordinator/package.json
  packages/@orbit/core/package.json
  packages/@orbit/data/package.json
  packages/@orbit/identity-map/package.json
  packages/@orbit/immutable/package.json
  packages/@orbit/indexeddb-bucket/package.json
  packages/@orbit/indexeddb/package.json
  packages/@orbit/jsonapi/package.json
  packages/@orbit/local-storage-bucket/package.json
  packages/@orbit/local-storage/package.json
  packages/@orbit/memory/package.json
  packages/@orbit/record-cache/package.json
  packages/@orbit/serializers/package.json
  packages/@orbit/store/package.json
  packages/@orbit/utils/package.json
Labels: breaking

#645 Update lerna and build scripts
  package.json
  packages/@orbit/coordinator/package.json
  packages/@orbit/core/package.json
  packages/@orbit/data/package.json
  packages/@orbit/identity-map/package.json
  packages/@orbit/immutable/package.json
  packages/@orbit/indexeddb-bucket/package.json
  packages/@orbit/indexeddb/package.json
  packages/@orbit/integration-tests/package.json
  packages/@orbit/jsonapi/package.json
  packages/@orbit/local-storage-bucket/package.json
  packages/@orbit/local-storage/package.json
  packages/@orbit/memory/package.json
  packages/@orbit/record-cache/package.json
  packages/@orbit/serializers/package.json
  packages/@orbit/store/package.json
  packages/@orbit/utils/package.json
  yarn.lock
Labels: internal

#642 Add {get|each}Attribute and {get|each}Relationship methods
  packages/@orbit/data/src/schema.ts
  packages/@orbit/data/test/schema-test.ts
Labels: enhancement

#639 @orbit/jsonapi-serializer operations (deserialize)
  packages/@orbit/jsonapi/src/jsonapi-serializer.ts
  packages/@orbit/jsonapi/src/resource-document.ts
  packages/@orbit/jsonapi/test/jsonapi-serializer-operations-test.ts
Labels: enhancement
