Repository orbitjs/orbit, pull requests merged in 2019-07, with the labels that each got.

#669 Add filter|sort|page support to findRelatedRecords queries
  packages/@orbit/data/src/query-expression.ts
  packages/@orbit/data/src/query-term.ts
  packages/@orbit/data/test/query-builder-test.ts
  packages/@orbit/jsonapi/src/lib/query-operators.ts
  packages/@orbit/jsonapi/test/jsonapi-source-test.ts
  packages/@orbit/record-cache/src/operators/async-patch-operators.ts
  packages/@orbit/record-cache/src/operators/async-query-operators.ts
  packages/@orbit/record-cache/src/operators/sync-patch-operators.ts
  packages/@orbit/record-cache/src/operators/sync-query-operators.ts
  packages/@orbit/record-cache/test/async-record-cache-test.ts
  packages/@orbit/record-cache/test/sync-record-cache-test.ts
Labels: enhancement

#671 Introduce explicit source activation + deactivation
  packages/@orbit/coordinator/src/strategies/log-truncation-strategy.ts
  packages/@orbit/coordinator/src/strategy.ts
  packages/@orbit/coordinator/test/strategy-test.ts
  packages/@orbit/data/src/source-interfaces/pullable.ts
  packages/@orbit/data/src/source-interfaces/pushable.ts
  packages/@orbit/data/src/source-interfaces/queryable.ts
  packages/@orbit/data/src/source-interfaces/syncable.ts
  packages/@orbit/data/src/source-interfaces/updatable.ts
  packages/@orbit/data/src/source.ts
  packages/@orbit/data/test/source-test.ts
  packages/@orbit/integration-tests/test/memory-bucket-test.ts
Labels: bug, enhancement

#672 Clean up yarn.lock interdependencies
  packages/@orbit/coordinator/yarn.lock
  packages/@orbit/core/yarn.lock
  packages/@orbit/data/yarn.lock
  packages/@orbit/identity-map/yarn.lock
  packages/@orbit/indexeddb-bucket/yarn.lock
  packages/@orbit/indexeddb/yarn.lock
  packages/@orbit/integration-tests/yarn.lock
  packages/@orbit/jsonapi/yarn.lock
  packages/@orbit/local-storage-bucket/yarn.lock
  packages/@orbit/local-storage/yarn.lock
  packages/@orbit/memory/yarn.lock
  packages/@orbit/record-cache/yarn.lock
  packages/@orbit/store/yarn.lock
Labels: internal

#668 Expose meta and links from processors to source
  packages/@orbit/jsonapi/src/lib/query-operators.ts
  packages/@orbit/jsonapi/src/lib/transform-requests.ts
  packages/@orbit/jsonapi/test/lib/query-operators-test.ts
  packages/@orbit/jsonapi/test/lib/transform-requests-test.ts
Labels: enhancement

#673 Ensure that cancelled tasks in queues have promises rejected
  packages/@orbit/core/src/task-processor.ts
  packages/@orbit/core/src/task-queue.ts
  packages/@orbit/core/test/task-processor-test.ts
  packages/@orbit/core/test/task-queue-test.ts
Labels: bug, enhancement

#677 Convert source interface implementations to use async/await
  packages/@orbit/data/src/source-interfaces/pullable.ts
  packages/@orbit/data/src/source-interfaces/pushable.ts
  packages/@orbit/data/src/source-interfaces/queryable.ts
  packages/@orbit/data/src/source-interfaces/syncable.ts
  packages/@orbit/data/src/source-interfaces/updatable.ts
Labels: internal

#678 [BREAKING] Shift some responsibilities for transform-related interfaces to source implementations
  packages/@orbit/data/src/source-interfaces/pullable.ts
  packages/@orbit/data/src/source-interfaces/pushable.ts
  packages/@orbit/data/src/source-interfaces/syncable.ts
  packages/@orbit/data/src/source-interfaces/updatable.ts
  packages/@orbit/data/test/source-interfaces/pullable-test.ts
  packages/@orbit/data/test/source-interfaces/pushable-test.ts
  packages/@orbit/data/test/source-interfaces/syncable-test.ts
  packages/@orbit/data/test/source-interfaces/updatable-test.ts
  packages/@orbit/indexeddb/src/source.ts
  packages/@orbit/indexeddb/test/source-test.ts
  packages/@orbit/jsonapi/src/jsonapi-source.ts
  packages/@orbit/jsonapi/test/jsonapi-source-test.ts
  packages/@orbit/local-storage/src/source.ts
  packages/@orbit/local-storage/test/source-test.ts
  packages/@orbit/memory/src/memory-source.ts
  packages/@orbit/memory/test/memory-source-test.ts
Labels: breaking

#680 [DEPRECATION] Deprecate `_transformed` in favor of `transformed`
  packages/@orbit/coordinator/test/strategies/log-truncation-strategy-test.ts
  packages/@orbit/coordinator/test/strategies/sync-strategy-test.ts
  packages/@orbit/data/src/source.ts
  packages/@orbit/data/test/source-interfaces/pullable-test.ts
  packages/@orbit/data/test/source-interfaces/pushable-test.ts
  packages/@orbit/data/test/source-interfaces/syncable-test.ts
  packages/@orbit/data/test/source-interfaces/updatable-test.ts
  packages/@orbit/data/test/source-test.ts
  packages/@orbit/indexeddb/src/source.ts
  packages/@orbit/jsonapi/src/jsonapi-source.ts
  packages/@orbit/local-storage/src/source.ts
  packages/@orbit/memory/src/memory-source.ts
Labels: enhancement
