Repository orbitjs/orbit, pull requests merged in 2020-07, with the labels that each got.

#762 Fix cache integrity processors' handling of relationships without explicit inverses.
  packages/@orbit/memory/test/memory-source-test.ts
  packages/@orbit/record-cache/src/operation-processors/utils/cache-integrity-utils.ts
  packages/@orbit/record-cache/test/async-record-cache-test.ts
  packages/@orbit/record-cache/test/sync-record-cache-test.ts
Labels: bug

#763 Backport PR 762 to v0.16
  packages/@orbit/record-cache/src/operation-processors/utils/cache-integrity-utils.ts
  packages/@orbit/record-cache/test/async-record-cache-test.ts
  packages/@orbit/record-cache/test/sync-record-cache-test.ts
Labels: bug

#764 Upgrade build dependencies (except snowpack)
  yarn.lock
Labels: dependencies, internal

#768 Update snowpack
  packages/@orbit/build/package.json
  yarn.lock
Labels: dependencies, internal

#770 Update snowpack
  packages/@orbit/build/package.json
  yarn.lock
Labels: dependencies, internal

#765 Add options to QueryExpression and Operation
  packages/@orbit/data/src/index.ts
  packages/@orbit/data/src/operation-term.ts
  packages/@orbit/data/src/operation.ts
  packages/@orbit/data/src/query-expression.ts
  packages/@orbit/data/src/query-term.ts
  packages/@orbit/data/src/transform-builder.ts
  packages/@orbit/data/src/transform.ts
  packages/@orbit/data/test/query-builder-test.ts
  packages/@orbit/data/test/transform-builder-test.ts
  packages/@orbit/data/test/transform-test.ts
  packages/@orbit/jsonapi/src/jsonapi-request-processor.ts
  packages/@orbit/jsonapi/src/lib/query-requests.ts
  packages/@orbit/jsonapi/src/lib/transform-requests.ts
  packages/@orbit/jsonapi/test/jsonapi-request-processor-test.ts
  packages/@orbit/memory/test/memory-cache-test.ts
  packages/@orbit/record-cache/src/async-record-cache.ts
  packages/@orbit/record-cache/src/sync-record-cache.ts
  packages/@orbit/record-cache/test/async-record-cache-test.ts
  packages/@orbit/record-cache/test/sync-record-cache-test.ts
Labels: enhancement
